site_name: Golang Learning
site_url: https://njoxpy.github.io/Lenguaje-Go/
site_author: Godbless Nyagawa
repo_url: https://github.com/Njoxpy/Lenguaje-Go
repo_name: GitHub

# Theme configuration
theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github_dark
  hljs_languages:
    - yaml
    - python
    - rust

  shortcuts:
    help: 191
    next: 78
    previous: 80
    search: 83
  prev_next_buttons_location: bottom
  navigation_depth: 3
  collapse_navigation: true
  titles_only: false
  sticky_navigation: true
  locale: en

# Navigation structure including your files
nav:
  - Home: index.md
  - Advice: advice/advice.md
  - Docs: intro/docs.md

  - Welcome & Basics (Tour Section 1):
      - Overview: "Welcome & Basics (Tour Section 1)/index.md"

  - Packages, Variables, Functions (17 parts):
      - Overview: "Packages, Variables, Functions (17 parts)/index.md"

  - Flow Control Statements:
      - Overview: controlflowstatements/index.md
  - More Types:
      - More Types: moretypes/index.md
      - Maps: moretypes/map.md
      - Functions: moretypes/functions.md
      - Named Returns: moretypes/namedreturns.md
      - Slices: moretypes/slices.md
      - Methods: methodsandinterfaces/methodsandinterfaces.md
      - Interfaces: methodsandinterfaces/interfaces.md

  - Concurrency: 
      - Introduction: intermediate/concurrency.md
      - Select: intermediate/select.md
      
  - Debugging: debugging/index.md
  - Testing: gotests/notes.md
  - Interviews: interviews/index.md

  - Questions:
      - Overview: "questions/questions.md"
      - Index: "questions/index.md"

  - Projects:
      - Overview: projects/projects.md

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

# Plugins
plugins:
  - search
